In [2]:
#going to the MTA website and appending multiple data file into the pandas dataframe.

import pandas as pd

links = ['http://web.mta.info/developers/data/nyct/turnstile/turnstile_180505.txt']#, 
         #'http://web.mta.info/developers/data/nyct/turnstile/turnstile_180512.txt',
        #'#http://web.mta.info/developers/data/nyct/turnstile/turnstile_180519.txt',
        #'http://web.mta.info/developers/data/nyct/turnstile/turnstile_180526.txt',
        #'http://web.mta.info/developers/data/nyct/turnstile/turnstile_180602.txt']

df = pd.concat([pd.read_csv(l) for l in links], ignore_index=True)

In [10]:
#df.head()
df.loc[(df.STATION == '59 ST')&(df.DATE=='05/05/2018')&(df.TIME=='20:00:00')]
#df.groupby(['STATION']).count()

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS
197207,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/05/2018,20:00:00,REGULAR,6608439,2239267
197249,A002,R051,02-00-01,59 ST,NQR456W,BMT,05/05/2018,20:00:00,REGULAR,5923042,1324909
197291,A002,R051,02-03-00,59 ST,NQR456W,BMT,05/05/2018,20:00:00,REGULAR,1072176,3993743
197333,A002,R051,02-03-01,59 ST,NQR456W,BMT,05/05/2018,20:00:00,REGULAR,681969,1059465
197375,A002,R051,02-03-02,59 ST,NQR456W,BMT,05/05/2018,20:00:00,REGULAR,5764673,7857386
197417,A002,R051,02-03-03,59 ST,NQR456W,BMT,05/05/2018,20:00:00,REGULAR,5363274,6257521
197459,A002,R051,02-03-04,59 ST,NQR456W,BMT,05/05/2018,20:00:00,REGULAR,6696093,3527727
197501,A002,R051,02-03-05,59 ST,NQR456W,BMT,05/05/2018,20:00:00,REGULAR,10776680,1355291
197543,A002,R051,02-03-06,59 ST,NQR456W,BMT,05/05/2018,20:00:00,REGULAR,8478383,489858
197585,A002,R051,02-05-00,59 ST,NQR456W,BMT,05/05/2018,20:00:00,REGULAR,1521,0
197627,A002,R051,02-05-01,59 ST,NQR456W,BMT,05/05/2018,20:00:00,REGULAR,0,774
197669,A002,R051,02-06-00,59 ST,NQR456W,BMT,05/05/2018,20:00:00,REGULAR,7478839,159029
220077,C021,R212,00-00-00,59 ST,NRW,BMT,05/05/2018,20:00:00,REGULAR,8156478,4287778
220119,C021,R212,00-00-01,59 ST,NRW,BMT,05/05/2018,20:00:00,REGULAR,7641132,5378978
220161,C021,R212,00-00-02,59 ST,NRW,BMT,05/05/2018,20:00:00,REGULAR,2030307526,703028573
220203,C021,R212,00-00-03,59 ST,NRW,BMT,05/05/2018,20:00:00,REGULAR,13228060,14125035
220245,C022,R212,01-03-00,59 ST,NRW,BMT,05/05/2018,20:00:00,REGULAR,1307189,405611
220287,C022,R212,01-05-00,59 ST,NRW,BMT,05/05/2018,20:00:00,REGULAR,262575,65536
220329,C022,R212,01-05-01,59 ST,NRW,BMT,05/05/2018,20:00:00,REGULAR,0,376
220371,C022,R212,01-06-00,59 ST,NRW,BMT,05/05/2018,20:00:00,REGULAR,5577810,4057500
220413,C022,R212,01-06-01,59 ST,NRW,BMT,05/05/2018,20:00:00,REGULAR,10621003,3525592
351796,R244,R050,00-00-00,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,44143,111567
351838,R244,R050,00-00-01,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,8769140,8656661
351880,R244,R050,00-00-02,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,2948212,1841978
351922,R244,R050,00-00-03,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,101016,169296
351964,R244,R050,00-00-04,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,549412,2840854
352006,R244,R050,00-03-00,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,1693478,4221711
352048,R244,R050,00-03-01,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,1166007,3192571
352090,R244,R050,00-03-02,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,2727014,5306714
352132,R244,R050,00-06-00,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,1948110,1306894
352174,R244,R050,00-06-01,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,3599359,1169438
352216,R244,R050,00-06-02,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,5182331,1091775
352258,R244A,R050,01-00-00,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,4350464,17077485
352300,R244A,R050,01-00-01,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,6041001,3231596
352342,R244A,R050,01-00-02,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,17396358,6560276
352384,R244A,R050,01-00-03,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,7488478,1567201
352426,R244A,R050,01-00-04,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,4308767,731552
352468,R244A,R050,01-06-00,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,7813997,9676244
352510,R244A,R050,01-06-01,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,4615537,2841887
352552,R245,R051,00-00-00,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,703854022,721664826
352594,R245,R051,00-03-00,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,10862742,10195147
352636,R245,R051,00-03-01,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,5959241,14560979
352678,R245,R051,00-03-02,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,1040658263,736229636
352720,R245,R051,00-03-03,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,6113629,12813942
352762,R245,R051,00-05-00,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,291626,250477
352804,R245,R051,00-05-01,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,12615963,5417727
352846,R245,R051,00-05-02,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,7125975,1350366
352888,R245A,R051,01-00-00,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,11498370,4036495
352930,R245A,R051,01-00-01,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,11739517,5949277
352972,R245A,R051,01-00-02,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,6195207,9508047
353014,R245A,R051,01-00-03,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,2476845,4845945
353056,R245A,R051,01-06-00,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,3182899,4306676
353098,R245A,R051,01-06-01,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,460259,16427

In [11]:
#creating two filters before create a filtered dataframe
filter_1 = df[df['TIME'] == '16:00:00']
filter_2 = df[df['TIME'] == '20:00:00']

In [14]:
#creating a filtered dataframe based in time 
filtered_df = pd.concat([filter_1, filter_2])
#filtered_df.count()
filtered_df.loc[(df.STATION == '59 ST')&(df.DATE=='05/05/2018')]

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS
197206,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/05/2018,16:00:00,REGULAR,6608151,2239219
197248,A002,R051,02-00-01,59 ST,NQR456W,BMT,05/05/2018,16:00:00,REGULAR,5922788,1324873
197290,A002,R051,02-03-00,59 ST,NQR456W,BMT,05/05/2018,16:00:00,REGULAR,1072054,3993485
197332,A002,R051,02-03-01,59 ST,NQR456W,BMT,05/05/2018,16:00:00,REGULAR,681673,1059170
197374,A002,R051,02-03-02,59 ST,NQR456W,BMT,05/05/2018,16:00:00,REGULAR,5764386,7857177
197416,A002,R051,02-03-03,59 ST,NQR456W,BMT,05/05/2018,16:00:00,REGULAR,5363041,6257413
197458,A002,R051,02-03-04,59 ST,NQR456W,BMT,05/05/2018,16:00:00,REGULAR,6695844,3527675
197500,A002,R051,02-03-05,59 ST,NQR456W,BMT,05/05/2018,16:00:00,REGULAR,10776274,1355265
197542,A002,R051,02-03-06,59 ST,NQR456W,BMT,05/05/2018,16:00:00,REGULAR,8478140,489847
197584,A002,R051,02-05-00,59 ST,NQR456W,BMT,05/05/2018,16:00:00,REGULAR,1521,0
197626,A002,R051,02-05-01,59 ST,NQR456W,BMT,05/05/2018,16:00:00,REGULAR,0,774
197668,A002,R051,02-06-00,59 ST,NQR456W,BMT,05/05/2018,16:00:00,REGULAR,7478641,159022
220076,C021,R212,00-00-00,59 ST,NRW,BMT,05/05/2018,16:00:00,REGULAR,8156136,4287487
220118,C021,R212,00-00-01,59 ST,NRW,BMT,05/05/2018,16:00:00,REGULAR,7640889,5378762
220160,C021,R212,00-00-02,59 ST,NRW,BMT,05/05/2018,16:00:00,REGULAR,2030307802,703028798
220202,C021,R212,00-00-03,59 ST,NRW,BMT,05/05/2018,16:00:00,REGULAR,13227685,14124707
220244,C022,R212,01-03-00,59 ST,NRW,BMT,05/05/2018,16:00:00,REGULAR,1307028,405520
220286,C022,R212,01-05-00,59 ST,NRW,BMT,05/05/2018,16:00:00,REGULAR,262574,65536
220328,C022,R212,01-05-01,59 ST,NRW,BMT,05/05/2018,16:00:00,REGULAR,0,375
220370,C022,R212,01-06-00,59 ST,NRW,BMT,05/05/2018,16:00:00,REGULAR,5577635,4057435
220412,C022,R212,01-06-01,59 ST,NRW,BMT,05/05/2018,16:00:00,REGULAR,10620830,3525521
351795,R244,R050,00-00-00,59 ST,456NQRW,IRT,05/05/2018,16:00:00,REGULAR,43986,111227
351837,R244,R050,00-00-01,59 ST,456NQRW,IRT,05/05/2018,16:00:00,REGULAR,8768986,8656475
351879,R244,R050,00-00-02,59 ST,456NQRW,IRT,05/05/2018,16:00:00,REGULAR,2948134,1841931
351921,R244,R050,00-00-03,59 ST,456NQRW,IRT,05/05/2018,16:00:00,REGULAR,100993,169237
351963,R244,R050,00-00-04,59 ST,456NQRW,IRT,05/05/2018,16:00:00,REGULAR,549405,2840733
352005,R244,R050,00-03-00,59 ST,456NQRW,IRT,05/05/2018,16:00:00,REGULAR,1693347,4221462
352047,R244,R050,00-03-01,59 ST,456NQRW,IRT,05/05/2018,16:00:00,REGULAR,1165814,3192296
352089,R244,R050,00-03-02,59 ST,456NQRW,IRT,05/05/2018,16:00:00,REGULAR,2726776,5306545
352131,R244,R050,00-06-00,59 ST,456NQRW,IRT,05/05/2018,16:00:00,REGULAR,1947968,1306797
...,...,...,...,...,...,...,...,...,...,...,...
351880,R244,R050,00-00-02,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,2948212,1841978
351922,R244,R050,00-00-03,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,101016,169296
351964,R244,R050,00-00-04,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,549412,2840854
352006,R244,R050,00-03-00,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,1693478,4221711
352048,R244,R050,00-03-01,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,1166007,3192571
352090,R244,R050,00-03-02,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,2727014,5306714
352132,R244,R050,00-06-00,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,1948110,1306894
352174,R244,R050,00-06-01,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,3599359,1169438
352216,R244,R050,00-06-02,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,5182331,1091775
352258,R244A,R050,01-00-00,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,4350464,17077485
352300,R244A,R050,01-00-01,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,6041001,3231596
352342,R244A,R050,01-00-02,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,17396358,6560276
352384,R244A,R050,01-00-03,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,7488478,1567201
352426,R244A,R050,01-00-04,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,4308767,731552
352468,R244A,R050,01-06-00,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,7813997,9676244
352510,R244A,R050,01-06-01,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,4615537,2841887
352552,R245,R051,00-00-00,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,703854022,721664826
352594,R245,R051,00-03-00,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,10862742,10195147
352636,R245,R051,00-03-01,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,5959241,14560979
352678,R245,R051,00-03-02,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,1040658263,736229636
352720,R245,R051,00-03-03,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,6113629,12813942
352762,R245,R051,00-05-00,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,291626,250477
352804,R245,R051,00-05-01,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,12615963,5417727
352846,R245,R051,00-05-02,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,7125975,1350366
352888,R245A,R051,01-00-00,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,11498370,4036495
352930,R245A,R051,01-00-01,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,11739517,5949277
352972,R245A,R051,01-00-02,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,6195207,9508047
353014,R245A,R051,01-00-03,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,2476845,4845945
353056,R245A,R051,01-06-00,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,3182899,4306676
353098,R245A,R051,01-06-01,59 ST,456NQRW,IRT,05/05/2018,20:00:00,REGULAR,460259,16427

In [2]:
import pandas as pd

files = ['http://web.mta.info/developers/data/nyct/turnstile/turnstile_180505.txt']

df1 = pd.concat([pd.read_csv(f) for f in files], ignore_index=True)
df1.head()

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/28/2018,00:00:00,REGULAR,6598847,2235829
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/28/2018,04:00:00,REGULAR,6598864,2235830
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/28/2018,08:00:00,REGULAR,6598880,2235863
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/28/2018,12:00:00,REGULAR,6598961,2235955
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/28/2018,16:00:00,REGULAR,6599175,2236015

In [6]:
 df1_subset = df1[:1001]

In [8]:
df1_subset.head(10)

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/28/2018,00:00:00,REGULAR,6598847,2235829
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/28/2018,04:00:00,REGULAR,6598864,2235830
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/28/2018,08:00:00,REGULAR,6598880,2235863
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/28/2018,12:00:00,REGULAR,6598961,2235955
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/28/2018,16:00:00,REGULAR,6599175,2236015
5,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/28/2018,20:00:00,REGULAR,6599456,2236074
6,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/29/2018,00:00:00,REGULAR,6599584,2236102
7,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/29/2018,04:00:00,REGULAR,6599593,2236106
8,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/29/2018,08:00:00,REGULAR,6599603,2236123
9,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/29/2018,12:00:00,REGULAR,6599689,2236180

In [20]:
filter_1 = df1_subset[df1_subset['TIME'] == '16:00:00']
filter_2 = df1_subset[df1_subset['TIME'] == '20:00:00']

In [27]:
temp = pd.concat([filter_1, filter_2])

In [28]:
temp

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/28/2018,16:00:00,REGULAR,6599175,2236015
10,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/29/2018,16:00:00,REGULAR,6599850,2236232
16,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/30/2018,16:00:00,REGULAR,6600769,2236736
22,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/01/2018,16:00:00,REGULAR,6602286,2237312
28,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/02/2018,16:00:00,REGULAR,6603787,2237877
34,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/03/2018,16:00:00,REGULAR,6605297,2238434
40,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/04/2018,16:00:00,REGULAR,6606840,2238949
46,A002,R051,02-00-01,59 ST,NQR456W,BMT,04/28/2018,16:00:00,REGULAR,5915662,1323201
52,A002,R051,02-00-01,59 ST,NQR456W,BMT,04/29/2018,16:00:00,REGULAR,5916254,1323287
58,A002,R051,02-00-01,59 ST,NQR456W,BMT,04/30/2018,16:00:00,REGULAR,5917035,1323572
64,A002,R051,02-00-01,59 ST,NQR456W,BMT,05/01/2018,16:00:00,REGULAR,5918181,1323867
70,A002,R051,02-00-01,59 ST,NQR456W,BMT,05/02/2018,16:00:00,REGULAR,5919340,1324134
76,A002,R051,02-00-01,59 ST,NQR456W,BMT,05/03/2018,16:00:00,REGULAR,5920528,1324404
82,A002,R051,02-00-01,59 ST,NQR456W,BMT,05/04/2018,16:00:00,REGULAR,5921725,1324679
88,A002,R051,02-03-00,59 ST,NQR456W,BMT,04/28/2018,16:00:00,REGULAR,1068646,3980531
94,A002,R051,02-03-00,59 ST,NQR456W,BMT,04/29/2018,16:00:00,REGULAR,1068999,3981470
100,A002,R051,02-03-00,59 ST,NQR456W,BMT,04/30/2018,16:00:00,REGULAR,1069305,3983226
106,A002,R051,02-03-00,59 ST,NQR456W,BMT,05/01/2018,16:00:00,REGULAR,1069812,3985472
112,A002,R051,02-03-00,59 ST,NQR456W,BMT,05/02/2018,16:00:00,REGULAR,1070362,3987708
118,A002,R051,02-03-00,59 ST,NQR456W,BMT,05/03/2018,16:00:00,REGULAR,1070943,3989971
124,A002,R051,02-03-00,59 ST,NQR456W,BMT,05/04/2018,16:00:00,REGULAR,1071531,3992090
130,A002,R051,02-03-01,59 ST,NQR456W,BMT,04/28/2018,16:00:00,REGULAR,673266,1046794
136,A002,R051,02-03-01,59 ST,NQR456W,BMT,04/29/2018,16:00:00,REGULAR,674074,1047905
142,A002,R051,02-03-01,59 ST,NQR456W,BMT,04/30/2018,16:00:00,REGULAR,674962,1049645
148,A002,R051,02-03-01,59 ST,NQR456W,BMT,05/01/2018,16:00:00,REGULAR,676300,1051673
154,A002,R051,02-03-01,59 ST,NQR456W,BMT,05/02/2018,16:00:00,REGULAR,677701,1053731
160,A002,R051,02-03-01,59 ST,NQR456W,BMT,05/03/2018,16:00:00,REGULAR,679059,1055808
166,A002,R051,02-03-01,59 ST,NQR456W,BMT,05/04/2018,16:00:00,REGULAR,680472,1057800
172,A002,R051,02-03-02,59 ST,NQR456W,BMT,04/28/2018,16:00:00,REGULAR,5755910,7847934
178,A002,R051,02-03-02,59 ST,NQR456W,BMT,04/29/2018,16:00:00,REGULAR,5756692,7848666
...,...,...,...,...,...,...,...,...,...,...,...
329,A002,R051,02-03-05,59 ST,NQR456W,BMT,05/03/2018,20:00:00,REGULAR,10772967,1355081
335,A002,R051,02-03-05,59 ST,NQR456W,BMT,05/04/2018,20:00:00,REGULAR,10775243,1355213
341,A002,R051,02-03-06,59 ST,NQR456W,BMT,04/28/2018,20:00:00,REGULAR,8467228,489690
347,A002,R051,02-03-06,59 ST,NQR456W,BMT,04/29/2018,20:00:00,REGULAR,8467959,489702
353,A002,R051,02-03-06,59 ST,NQR456W,BMT,04/30/2018,20:00:00,REGULAR,8469638,489722
359,A002,R051,02-03-06,59 ST,NQR456W,BMT,05/01/2018,20:00:00,REGULAR,8471483,489743
365,A002,R051,02-03-06,59 ST,NQR456W,BMT,05/02/2018,20:00:00,REGULAR,8473339,489765
371,A002,R051,02-03-06,59 ST,NQR456W,BMT,05/03/2018,20:00:00,REGULAR,8475230,489807
377,A002,R051,02-03-06,59 ST,NQR456W,BMT,05/04/2018,20:00:00,REGULAR,8477417,489832
383,A002,R051,02-05-00,59 ST,NQR456W,BMT,04/28/2018,20:00:00,REGULAR,1516,0
389,A002,R051,02-05-00,59 ST,NQR456W,BMT,04/29/2018,20:00:00,REGULAR,1517,0
395,A002,R051,02-05-00,59 ST,NQR456W,BMT,04/30/2018,20:00:00,REGULAR,1517,0
401,A002,R051,02-05-00,59 ST,NQR456W,BMT,05/01/2018,20:00:00,REGULAR,1517,0
407,A002,R051,02-05-00,59 ST,NQR456W,BMT,05/02/2018,20:00:00,REGULAR,1517,0
413,A002,R051,02-05-00,59 ST,NQR456W,BMT,05/03/2018,20:00:00,REGULAR,1517,0
419,A002,R051,02-05-00,59 ST,NQR456W,BMT,05/04/2018,20:00:00,REGULAR,1521,0
425,A002,R051,02-05-01,59 ST,NQR456W,BMT,04/28/2018,20:00:00,REGULAR,0,772
431,A002,R051,02-05-01,59 ST,NQR456W,BMT,04/29/2018,20:00:00,REGULAR,0,772
437,A002,R051,02-05-01,59 ST,NQR456W,BMT,04/30/2018,20:00:00,REGULAR,0,772
443,A002,R051,02-05-01,59 ST,NQR456W,BMT,05/01/2018,20:00:00,REGULAR,0,772
449,A002,R051,02-05-01,59 ST,NQR456W,BMT,05/02/2018,20:00:00,REGULAR,0,772
455,A002,R051,02-05-01,59 ST,NQR456W,BMT,05/03/2018,20:00:00,REGULAR,0,772
461,A002,R051,02-05-01,59 ST,NQR456W,BMT,05/04/2018,20:00:00,REGULAR,0,774
467,A002,R051,02-06-00,59 ST,NQR456W,BMT,04/28/2018,20:00:00,REGULAR,7472920,158851
473,A002,R051,02-06-00,59 ST,NQR456W,BMT,04/29/2018,20:00:00,REGULAR,7473301,158868
479,A002,R051,02-06-00,59 ST,NQR456W,BMT,04/30/2018,20:00:00,REGULAR,7474309,158895
485,A002,R051,02-06-00,59 ST,NQR456W,BMT,05/01/2018,20:00:00,REGULAR,7475423,158928
491,A002,R051,02-06-00,59 ST,NQR456W,BMT,05/02/2018,20:00:00,REGULAR,7476612,158955
497,A002,R051,02-06-00,59 ST,NQR456W,BMT,05/03/2018,20:00:00,REGULAR,7477798,158980
503,A002,R051,02-06-00,59 ST,NQR456W,BMT,05/04/2018,20:00:00,REGULAR,7478324,159006